test: 我是配置中心配置信息
marathon-lb.bo.domainname: marathon-lb-bo.marathon.mesos
app.datasource.bar.url: jdbc:oracle:thin:@134.32.30.131:3521:sibil4db
app.datasource.bar.username: ucr_bil_acct
app.datasource.bar.password: SI_shaoyong123
app.datasource.bar.driver-class-name: oracle.jdbc.driver.OracleDriver
