app.datasource.actdb1.url: jdbc:oracle:thin:@134.32.30.132:3521:siact1db
app.datasource.actdb1.username: si_shaoyong
app.datasource.actdb1.password: stc_xiao9672
app.datasource.actdb1.driver-class-name: oracle.jdbc.driver.OracleDriver
